version: "3"
services:
  envoy:
    image: envoyproxy/envoy-dev:0bb12b182d18460e787b3e6b47dfeb36e717b1a4
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "10000:10000"
  redis:
    image: bitnami/redis
    volumes:
      - ./src/redis:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
